import { NextResponse } from "next/server"

function buildPrompt(dataset: string, scenario: string, colorScheme: string, customPrompt?: string): string {
  // Use custom prompt if provided
  if (customPrompt && customPrompt.trim()) {
    let prompt = customPrompt.trim()

    // Add color scheme to custom prompt
    const colorPrompts: Record<string, string> = {
      plasma: "vibrant plasma colors, electric blues and magentas",
      quantum: "quantum field colors, deep blues and ethereal whites",
      cosmic: "cosmic colors, deep space purples and stellar golds",
      thermal: "thermal imaging colors, heat signature reds and oranges",
      spectral: "full spectrum rainbow colors, prismatic light effects",
      crystalline: "crystalline colors, clear gems and mineral tones",
      bioluminescent: "bioluminescent colors, glowing organic blues and greens",
      aurora: "aurora borealis colors, dancing green and purple lights",
      metallic: "metallic tones, silver and bronze accents",
      prismatic: "prismatic light effects, rainbow refractions",
      monochromatic: "monochromatic grayscale, black and white tones",
      infrared: "infrared heat colors, thermal reds and oranges",
      lava: "molten lava colors, glowing reds and oranges",
      futuristic: "futuristic neon colors, cyberpunk aesthetics",
      forest: "forest greens and earth tones",
      ocean: "ocean blues and aqua tones",
      sunset: "warm sunset colors, oranges and deep reds",
      arctic: "arctic colors, ice blues and pristine whites",
      neon: "bright neon colors, electric pinks and greens",
      vintage: "vintage sepia tones, aged photograph aesthetics",
      toxic: "toxic green colors, radioactive aesthetics",
      ember: "glowing ember colors, warm orange and red coals",
      lunar: "lunar surface colors, silver grays and crater shadows",
      tidal: "tidal pool colors, ocean blues and sandy browns",
    }

    prompt += `, ${colorPrompts[colorScheme] || "vibrant colors"}`
    prompt +=
      ", highly detailed, artistic masterpiece, professional photography quality, 8K resolution, stunning visual composition"

    return prompt
  }

  // Build dataset-specific prompt
  let prompt = ""

  // Dataset-specific base prompts
  const datasetPrompts: Record<string, string> = {
    nuanu:
      "Nuanu Creative City architectural elements, modern creative spaces, innovative design, futuristic urban planning",
    bali: "Balinese Hindu temples, traditional architecture, tropical paradise, sacred geometry, rice terraces",
    thailand: "Thai Buddhist temples, golden spires, traditional architecture, serene landscapes, lotus flowers",
    indonesian: "Indonesian cultural heritage, traditional patterns, mystical elements, archipelago beauty",
    horror: "Indonesian mystical creatures, supernatural folklore elements, traditional legends",
    spirals: "Spiral patterns, organic sequences, golden ratio, geometric precision",
    fractal: "Fractal patterns, recursive geometry, infinite detail, abstract beauty",
    mandelbrot: "Complex pattern visualization, infinite zoom patterns",
    julia: "Abstract set patterns, iterative patterns",
    lorenz: "Attractor patterns, chaos theory visualization, butterfly effect patterns",
    hyperbolic: "Hyperbolic geometry, non-Euclidean space, curved surfaces",
    gaussian: "Field visualization, statistical distributions, probability landscapes",
    cellular: "Cellular automata patterns, emergent complexity",
    voronoi: "Voronoi diagrams, spatial partitioning, natural tessellation patterns",
    perlin: "Perlin noise landscapes, procedural generation, organic randomness",
    diffusion: "Reaction-diffusion patterns, chemical wave propagation, Turing patterns",
    wave: "Wave interference patterns, harmonic oscillations, frequency visualizations",
    moons: "Lunar orbital mechanics, celestial body movements, gravitational dance",
    tribes: "Tribal network topology, social connections, community structures",
    heads: "Mosaic head compositions, portrait arrangements, facial geometry",
    natives: "Ancient native tribes, traditional cultures, indigenous wisdom",
    statues: "Sacred sculptural statues, carved monuments, artistic figures",
    "8bit": "8bit pixel art, retro gaming aesthetics, pixelated graphics, classic arcade style",
  }

  prompt = datasetPrompts[dataset] || "Abstract mathematical art"

  // Add scenario-specific details for 8bit dataset
  if (dataset === "8bit") {
    const scenarioPrompts: Record<string, string> = {
      pure: "pure mathematical beauty with 8bit pixel aesthetics and retro gaming precision",
      "glitch-matrix":
        "GLITCH MATRIX CHAOS: Corrupted digital reality with cascading data streams in authentic 8bit pixel art, system error artifacts manifesting as beautiful pixel corruption patterns, matrix-style falling code rendered in blocky 8bit characters, digital reality fragmenting into geometric pixel shards, corrupted memory blocks creating abstract pixel art compositions, data overflow visualized as pixel waterfalls of green and amber code, system crash aesthetics with beautiful pixel debris, digital noise patterns creating mesmerizing 8bit static art, corrupted sprite data manifesting as surreal pixel creatures, glitch art effects with authentic retro gaming color palette limitations, cascading binary code in pixel typography, digital reality tears revealing underlying 8bit architecture, memory leak visualizations as flowing pixel streams, corrupted texture mapping creating abstract 8bit landscapes, system error messages as decorative pixel art elements, digital archaeology of broken 8bit worlds",
      "neon-synthwave":
        "NEON SYNTHWAVE DREAMS: Retro-futuristic landscapes rendered in vibrant 8bit pixel art with pulsing neon grid systems, synthwave aesthetic with authentic pixel limitations and chromatic aberration effects, neon-lit highways stretching into pixel horizons with grid-lined roads, retro sports cars as sleek 8bit sprites racing through neon cityscapes, palm trees silhouetted against pixel sunsets in hot pink and cyan, laser grid effects creating geometric 8bit patterns, synthwave mountains with wireframe pixel outlines, neon signs and holographic advertisements in limited 8bit color palettes, retro-futuristic architecture with glowing pixel details, 80s aesthetic translated into authentic pixel art form, chromatic aberration effects using pixel color bleeding, synthwave characters in pixel form wearing neon clothing, laser light shows creating geometric pixel art displays, retro computer interfaces with glowing 8bit elements, nostalgic 80s atmosphere with authentic pixel art limitations, digital sunset gradients with pixel color banding effects",
      "pixel-storm":
        "PIXEL STORM VORTEX: Swirling maelstrom of animated pixels creating hypnotic geometric patterns in authentic 8bit style, tornado of pure pixel energy with individual blocks visible in the chaos, pixel particles forming spiral galaxies and vortex patterns, storm clouds made of clustered 8bit pixels in dark color palettes, lightning effects rendered as jagged pixel bolts with electric blue highlights, pixel rain falling in geometric patterns with authentic 8bit physics, whirlwind of colored pixels creating rainbow spiral effects, pixel debris caught in digital tornadoes, storm eye revealing calm pixel art landscapes, chaotic pixel weather systems with authentic retro gaming aesthetics, pixel hail and snow effects using white and gray blocks, digital storm clouds with pixel-perfect cumulus formations, pixel wind effects showing directional flow patterns, storm surge of pixels creating tidal wave effects, electric pixel storms with authentic 8bit color limitations, meteorological pixel phenomena with retro gaming charm",
      "digital-decay":
        "DIGITAL DECAY APOCALYPSE: Post-digital wasteland with fragmenting pixels and corrupted memory blocks in authentic 8bit style, abandoned digital cities with crumbling pixel architecture, corrupted data manifesting as beautiful pixel decay patterns, digital rust and erosion effects using authentic 8bit color degradation, fragmenting pixel structures revealing underlying code architecture, memory corruption creating abstract 8bit art compositions, digital archaeology of forgotten 8bit worlds, pixel graveyards with tombstone-like data structures, corrupted sprite data creating surreal pixel creatures, digital entropy visualized through pixel degradation, system failure aesthetics with beautiful pixel debris, abandoned digital infrastructure with overgrown pixel vegetation, corrupted texture files creating abstract 8bit landscapes, digital fossils of ancient 8bit civilizations, memory leak visualizations as flowing pixel streams, post-apocalyptic pixel environments with authentic retro gaming atmosphere",
      "quantum-bits":
        "QUANTUM BIT DIMENSIONS: Microscopic 8bit universes with quantum pixel fluctuations and probability clouds in authentic pixel art style, quantum superposition visualized through overlapping pixel states, probability waves rendered as flowing 8bit particle effects, quantum entanglement shown through connected pixel pairs, microscopic 8bit worlds existing in quantum dimensions, particle physics visualized through authentic pixel art aesthetics, quantum tunneling effects with pixels phasing through barriers, wave-particle duality shown through 8bit animation cycles, quantum field fluctuations creating pixel static patterns, subatomic 8bit particles with authentic color limitations, quantum mechanics translated into retro gaming visual language, probability clouds as pixel fog effects, quantum interference patterns in 8bit geometric forms, microscopic pixel universes with their own physics, quantum computing visualized through 8bit data processing, dimensional pixel portals showing quantum realm access",
      "retro-cosmos":
        "RETRO COSMIC GENESIS: 8bit interpretation of cosmic creation with pixelated nebulae and digital star formation in authentic retro gaming style, cosmic big bang rendered as expanding pixel explosion, stellar nurseries with baby stars as glowing 8bit sprites, galaxy formation through swirling pixel spiral arms, cosmic dust clouds rendered in authentic 8bit particle effects, planetary formation with pixel accretion disks, solar systems with pixelated planets and orbital mechanics, cosmic radiation visualized as pixel particle streams, black holes with pixel event horizons and accretion effects, cosmic microwave background as 8bit static patterns, stellar evolution from pixel proto-stars to pixel supernovas, cosmic web structure with pixel filaments connecting galaxies, asteroid belts as pixel debris fields, cosmic phenomena translated into retro gaming visual language, space-time curvature shown through pixel grid distortions, cosmic creation myths visualized through authentic 8bit aesthetics",
      "cyber-mandala":
        "CYBER MANDALA MEDITATION: Sacred geometric patterns rendered in pure 8bit precision with digital enlightenment themes, mandala formations using authentic pixel art techniques, sacred geometry translated into retro gaming visual language, digital meditation spaces with pixel lotus patterns, cyber-spiritual symbols in 8bit geometric forms, mandala animations using authentic pixel art frame cycles, digital prayer wheels with rotating pixel patterns, sacred pixel art with authentic color palette limitations, cyber-buddhist aesthetics in retro gaming style, digital enlightenment visualized through 8bit transcendence effects, pixel chakras with authentic color representations, sacred digital architecture with mandala-inspired pixel layouts, cyber-spiritual energy flows as pixel particle streams, digital meditation gardens with pixel zen elements, sacred pixel geometry with mathematical precision, cyber-mandala portals to digital enlightenment realms",
      "pixel-fractals":
        "PIXEL FRACTAL INFINITY: Recursive 8bit patterns creating infinite depth with mathematical pixel precision, fractal mathematics translated into authentic pixel art form, recursive pixel patterns with authentic retro gaming aesthetics, infinite zoom effects using 8bit scaling techniques, mathematical beauty rendered through pixel art precision, fractal trees with pixel branches and authentic color limitations, recursive pixel spirals creating hypnotic patterns, mathematical infinity visualized through 8bit artistic expression, fractal landscapes with pixel terrain generation, recursive pixel art with authentic retro gaming charm, mathematical patterns using pure pixel precision, fractal animations with authentic 8bit frame cycles, infinite complexity achieved through simple pixel elements, mathematical art using authentic retro gaming techniques, fractal geometry translated into pixel art mastery, recursive beauty through authentic 8bit artistic expression",
      "data-cathedral":
        "DATA CATHEDRAL SANCTUM: Monumental digital architecture built from pure 8bit data structures and code poetry, cathedral spires made of stacked pixel blocks, gothic digital architecture with authentic 8bit construction techniques, data streams flowing like pixel waterfalls through cathedral spaces, code poetry inscribed in pixel typography on digital walls, sacred digital spaces with pixel stained glass windows, monumental pixel architecture with authentic retro gaming aesthetics, digital pipe organs with pixel keys and authentic sound wave visualizations, cathedral lighting effects using authentic 8bit illumination techniques, sacred digital geometry with pixel precision construction, data sanctuary with flowing information streams as pixel art, digital worship spaces with pixel congregation areas, sacred code architecture with authentic retro gaming visual language, monumental pixel construction with mathematical precision, digital cathedral acoustics visualized through 8bit sound wave patterns, sacred data architecture with authentic pixel art mastery",
      "electric-dreams":
        "ELECTRIC DREAMS SEQUENCE: Surreal 8bit dreamscapes with flowing electric currents and digital consciousness themes, dream logic translated into authentic pixel art form, electric sheep rendered as pixel sprites with authentic retro gaming aesthetics, digital consciousness streams as flowing pixel currents, surreal pixel landscapes with dream-like physics, electric dreams with authentic 8bit color palette limitations, digital sleep patterns visualized through pixel wave forms, consciousness uploading effects using authentic pixel art techniques, electric neural networks as pixel circuit patterns, digital dream architecture with impossible pixel geometry, electric thought patterns as pixel lightning effects, consciousness streams flowing through 8bit digital landscapes, electric dreams with authentic retro gaming visual language, digital REM sleep visualized through pixel animation cycles, electric consciousness with authentic 8bit artistic expression, surreal digital dreams with pixel art mastery",
      "pixel-phoenix":
        "PIXEL PHOENIX REBIRTH: Mythical digital creature emerging from cascading pixel flames and data resurrection themes, phoenix rising rendered in authentic 8bit pixel art style, digital rebirth through pixel flame effects, mythical pixel creature with authentic retro gaming aesthetics, cascading pixel fire with authentic color palette limitations, data resurrection visualized through pixel phoenix transformation, digital mythology translated into authentic pixel art form, phoenix flames as flowing pixel particle effects, mythical rebirth cycle using authentic 8bit animation techniques, digital phoenix with pixel feather details and authentic sprite work, resurrection fire effects using authentic retro gaming visual language, pixel phoenix soaring through digital skies, mythical transformation sequences in authentic 8bit style, digital rebirth mythology with pixel art mastery, phoenix rising from pixel ashes with authentic retro gaming charm, mythical digital creature with authentic 8bit artistic expression",
      "binary-blizzard":
        "BINARY BLIZZARD STORM: Chaotic snowstorm of 1s and 0s creating mesmerizing 8bit weather phenomena, binary code falling like pixel snow with authentic retro gaming aesthetics, digital blizzard effects using authentic 8bit particle systems, binary storm patterns with mathematical precision, code snowflakes as individual pixel elements, digital weather phenomena translated into authentic pixel art form, binary precipitation with authentic color palette limitations, digital storm systems with pixel meteorology, code blizzard creating beautiful 8bit static patterns, binary weather with authentic retro gaming visual language, digital snow accumulation using pixel physics, binary storm clouds with authentic 8bit formation patterns, code weather systems with pixel precision, digital blizzard landscapes with authentic pixel art mastery, binary storm effects with authentic retro gaming charm, mathematical weather phenomena through authentic 8bit artistic expression",
      "chrome-cascade":
        "CHROME CASCADE FALLS: Metallic pixel waterfalls with reflective chrome surfaces and liquid mercury effects, chrome pixel art with authentic metallic color palette limitations, liquid metal effects using authentic 8bit animation techniques, reflective pixel surfaces with authentic retro gaming aesthetics, metallic waterfalls cascading in pixel form, chrome pixel art with authentic sprite work and metallic shading, liquid mercury pools with authentic 8bit reflection effects, metallic pixel landscapes with chrome surface details, reflective pixel art using authentic retro gaming visual language, chrome cascade effects with authentic color palette limitations, metallic pixel physics with authentic 8bit fluid dynamics, chrome pixel art mastery with authentic retro gaming charm, liquid metal streams flowing through pixel landscapes, metallic pixel art with authentic artistic expression, chrome effects using authentic 8bit rendering techniques, reflective pixel mastery with authentic retro gaming aesthetics",
      "neon-labyrinth":
        "NEON LABYRINTH MAZE: Impossible 8bit maze structures with glowing pathways and digital minotaur guardians, maze architecture rendered in authentic pixel art style, neon pathways glowing with authentic 8bit color palette limitations, digital labyrinth with impossible pixel geometry, maze walls constructed from authentic pixel blocks, neon lighting effects using authentic retro gaming techniques, labyrinth guardians as pixel sprites with authentic animation cycles, maze puzzles with authentic 8bit game design aesthetics, neon maze corridors with authentic pixel art precision, digital labyrinth architecture with authentic retro gaming visual language, impossible maze geometry using authentic pixel construction techniques, neon maze lighting with authentic color palette limitations, labyrinth exploration with authentic 8bit adventure game aesthetics, maze architecture with authentic pixel art mastery, digital labyrinth with authentic retro gaming charm, neon maze effects with authentic 8bit artistic expression",
    }

    if (scenarioPrompts[scenario]) {
      prompt += ", " + scenarioPrompts[scenario]
    }
  }

  // Add scenario-specific details for Indonesian dataset
  if (dataset === "indonesian") {
    const scenarioPrompts: Record<string, string> = {
      pure: "pure mathematical beauty with Indonesian geometric patterns",
      garuda:
        "GODLEVEL BOSCH GARDEN OF EARTHLY DELIGHTS: Hieronymus Bosch's masterpiece triptych with iconic fantastical creatures, left panel showing Adam and Eve in pristine Garden of Eden with exotic hybrid animals - elephant-like creatures with castle towers on their backs, giraffe-necked beasts with human intelligence, fish-birds with translucent wings flying through crystalline air, God presenting Eve while strange creatures emerge from caves and crystal pools, middle panel exploding with naked humans riding giant strawberries and oversized fish through coral-pink landscapes, the famous tree-man with hollow egg-shaped body and branch legs standing in central lake, people emerging from and disappearing into giant mussel shells and transparent spheres, couples trapped inside glass bubbles floating through surreal gardens, riders on fantastic boar-fish hybrids and bird-headed quadrupeds, the iconic central fountain with nude figures dancing around pink tower topped with crescent moon, right panel depicting Hell with Bosch's terrifying demon orchestra - the famous bird-headed monster with human body devouring and excreting human souls, musical instruments transformed into torture devices with people trapped inside harps and drums, the knife-eared creature with bagpipe body and human legs, demons with human heads and animal bodies playing discordant music on bone instruments, burning cities reflected in dark waters, hybrid creatures with insect wings and mammalian bodies, organic architecture that breathes and bleeds, every detail painted with Bosch's characteristic precision showing scales, feathers, and human flesh with equal hyperrealistic clarity, 8K resolution capturing every symbolic creature and surreal transformation",
      wayang:
        "GODLEVEL BOSCH TEMPTATION OF SAINT ANTHONY: Hieronymus Bosch's nightmarish vision with most terrifying demon creations, Saint Anthony surrounded by signature hybrid monsters - famous fish-headed demons with human torsos and bird legs carrying the saint through apocalyptic skies, grotesque creatures with pig snouts and human hands emerging from burning ruins, iconic toad-like demons with bloated bellies and spindly limbs, demons disguised as beautiful women with hidden animal features - serpent tails coiling beneath silk robes, bird claws instead of hands, insect wings folded behind backs, characteristic egg-shaped creatures with human faces and stick-thin legs dancing in demonic processions, flying demons with bat wings and human heads playing discordant music on instruments made from bones and organs, famous hollow-tree demons with gaping mouths in their torsos containing smaller demons and tortured souls, creatures with multiple heads - human, animal, and bird - all speaking blasphemies in different tongues, demons with backwards feet and upside-down faces crawling on ceilings, signature monster with funnel-shaped head and ladder-like body, organic architecture that breathes and bleeds with windows that are eyes and doors that are mouths, demons emerging from split-open fruits and vegetables like rotten pomegranates birthing imps, terrifying bird-beaked creatures with human intelligence gleaming in their eyes, Saint Anthony maintaining divine composure while reading sacred texts as supernatural chaos swirls around him, every demon rendered with meticulous attention to anatomical impossibility yet convincing detail, 8K hyperrealistic precision showing every scale, feather, and grotesque transformation",
      batik:
        "GODLEVEL BOSCH SHIP OF FOOLS: Hieronymus Bosch's Ship of Fools populated with characteristic human-animal hybrids and moral grotesques, overcrowded boat filled with signature figures - monks with pig faces representing gluttony, their snouts dripping with wine and food, nuns with bird beaks symbolizing gossip and chatter, their beaks opening to reveal forked tongues, passengers with fish heads gasping for spiritual water while drowning in earthly wine, gills flapping uselessly in air, famous fool with funnel hat and egg-shaped body playing discordant music on organic instruments, demons disguised as merchants with coin-filled transparent bellies and claw hands counting money, creatures with human torsos and animal legs dancing drunkenly on deck - goat legs, horse hooves, bird talons, characteristic owl of false wisdom perched on mast with human-like intelligence and knowing smirk in its eyes, passengers transforming into their inner animal natures - becoming pigs with human hands still grasping wine cups, donkeys with human faces braying moral platitudes, birds with human bodies pecking at each other, ship's hull decorated with organic motifs that seem alive and breathing - carved faces that blink and mouths that whisper, water surrounding vessel filled with floating symbols of vanity - mirrors reflecting demon faces instead of human ones, crowns worn by fish swimming in circles, musical instruments played by sea creatures with human fingers, distant shoreline showing impossible architecture with towers that are giant musical instruments and buildings with faces that sing, tree-mast bearing fruits that are human heads in various expressions of folly - some laughing, some crying, some screaming, each passenger representing different interpretation of human vice with animal characteristics becoming more pronounced as moral decay progresses, 8K resolution showing every grotesque detail and symbolic transformation with signature precision",
      borobudur:
        "GODLEVEL BOSCH SEVEN DEADLY SINS WHEEL: Hieronymus Bosch's circular composition with signature creatures representing moral failure, central eye of God watching over humanity's transgressions with Christ emerging from pupil surrounded by angelic-demonic hybrids, seven segments radiating outward each illustrating different sin through detailed vignettes with Bosch's characteristic monsters, Pride shown through woman admiring reflection held by demon with bird head and human hands while mirror reveals her true animal nature - pig snout and peacock feathers, Envy depicted as neighbors coveting possessions with green-faced demons with elongated necks and grasping claws stoking jealousy between people transforming into envious beasts, Wrath illustrated through tavern brawl where participants are becoming their inner animals - pig-faced gluttons wielding kitchen knives, wolf-headed aggressors with human hands, bird-beaked screamers with talons extended, Sloth showing lazy figure surrounded by characteristic snail-demons and slug-creatures representing spiritual lethargy, creatures with human faces but gastropod bodies leaving trails of moral decay, Greed featuring merchant with coin-filled transparent belly while money-demons with insect features and claw hands count coins with mathematical precision, Gluttony displaying feast where diners are transforming into the animals they consume - pig snouts emerging from human faces, fish gills opening on necks, bird beaks replacing human mouths, Lust revealing couples in compromising positions observed by voyeuristic demons with multiple eyes and elongated necks, telescoping appendages for spying, four corner medallions showing Death as skeleton with signature scythe-wings, Judgment with Christ surrounded by hybrid angel-demons with both holy and demonic features, Hell populated with most creative torture-demons, and Glory with saints who retain subtle animal characteristics representing their spiritual virtues, every scene filled with impossible creatures that blend human intelligence with animal instincts, 8K hyperrealistic detail showing every moral transformation and demonic feature",
      komodo:
        "GODLEVEL BOSCH HAYWAIN TRIPTYCH: Hieronymus Bosch's Haywain featuring signature human-animal transformations and demonic creatures, left panel showing Creation with rebel angels transforming into characteristic insect-demons, bird-headed fallen angels with human torsos, hybrid creatures with human intelligence but animal bodies, central panel dominated by massive hay wagon pulled by signature demons disguised as ordinary beasts but with human intelligence gleaming in their eyes and hidden claws beneath fur, crowds of people from all social classes desperately grabbing hay while gradually transforming into their inner animal natures - nobles becoming preening peacocks with human hands, merchants growing pig snouts while counting coins, clergy developing bird beaks for pecking at worldly goods, Pope and Emperor following wagon on horseback while their mounts reveal demonic features - horse heads with human eyes and knowing expressions, lovers on haystack oblivious to spiritual danger while voyeuristic demons with telescoping necks and multiple eyes observe from hidden positions in the hay, demon musicians playing organic instruments that are part plant, part animal, part human anatomy - drums made from human torsos, flutes carved from bones, right panel revealing Hell as ultimate bestiary with burning landscape populated by most creative torture-demons - creatures with musical instrument bodies operating mechanical torture devices, bird-headed monsters with human hands and opposable thumbs, demons with transparent bellies showing their victims being digested, architectural impossibilities with buildings that are giant creatures with window-eyes and door-mouths, every figure throughout triptych showing genius for revealing inner spiritual state through gradual physical transformation into appropriate animal form, 8K resolution capturing every detail of moral metamorphosis and demonic creativity",
      dance:
        "GODLEVEL BOSCH LAST JUDGMENT: Hieronymus Bosch's terrifying Last Judgment with most creative demonic creatures and hybrid beings, Christ as judge displaying crucifixion wounds while surrounded by signature angel-demon hybrids with subtle animal features - wings that are part feather, part bat membrane, faces that blend human beauty with predatory bird characteristics, Virgin Mary and John the Baptist with characteristic blend of human beauty and otherworldly strangeness, angels blowing trumpets that are part instrument, part organic creature with breathing holes and pulsing veins, resurrected souls emerging from earth in various states of transformation - some retaining human form, others revealing their true animal natures based on earthly sins, blessed souls ascending toward heavenly light guided by benevolent angel-creatures with bird wings but human compassion in their eyes, damned souls dragged downward by most inventive demons - creatures with multiple heads (human, animal, insect), transparent bodies showing internal organs and digestive systems, limbs that are musical instruments playing eternal discord, fantastical punishments matching earthly crimes with creative torture-demons using organic instruments of torment, hybrid demon creatures with animal heads and human bodies administering eternal justice with tools that are part of their anatomy, landscape divided between heavenly paradise populated with gentle hybrid creatures and hellish wasteland filled with nightmarish creations, architectural marvels in heaven that are living creatures with beneficial purposes contrasting with Hell's buildings that are giant demons with window-eyes and door-mouths, saints and martyrs surrounding Christ's throne displaying instruments of martyrdom while showing subtle animal characteristics representing their spiritual virtues, 8K hyperrealistic detail capturing every soul's transformation and complete bestiary of moral creatures",
      volcanoes:
        "GODLEVEL BOSCH DEATH AND THE MISER: Hieronymus Bosch's Death and the Miser with signature demonic tempters and moral creatures, dying miser in bed reaching toward bag of gold while his body shows signs of transformation into his true animal nature - developing pig-like features representing greed, snout elongating and skin becoming coarse, angel pointing toward crucifix with characteristic blend of human beauty and bird-like ethereal qualities, Death entering chamber as skeleton with signature additions - crow wings sprouting from shoulder blades, serpent tail coiled beneath robes, human intelligence gleaming in empty eye sockets, demon emerging from beneath bed as one of classic tempter-creatures with human torso, animal legs ending in cloven hooves, seductive human face hiding predatory animal teeth, room filled with symbols of worldly wealth that reveal their true nature under vision - coins that are demon eyes blinking and watching, jewelry that writhes like living serpents, fine fabrics that show patterns of human faces in torment, younger version of miser in background storing gold in chest while characteristic money-demons with insect features and transparent bellies full of coins whisper encouragement with forked tongues, moral choice visualized through miser's gesture reaching simultaneously toward money (guarded by pig-faced greed demons) and salvation (protected by dove-winged mercy angels), architectural details showing luxury household where every ornate furnishing contains hidden creatures - chair legs that are demon claws, tapestries that show scenes of moral transformation, symbolic objects throughout room representing vanity's true nature - mirrors reflecting animal faces instead of human ones, books whose pages flutter like bat wings, 8K resolution showing every symbolic detail and complete moral bestiary",
      temples:
        "GODLEVEL BOSCH THE CONJURER: Hieronymus Bosch's satirical Conjurer scene with signature trickster creatures and moral grotesques, central conjurer performing cup-and-ball trick while his true nature revealed through subtle animal features - elongated fingers like bird talons, eyes with reptilian pupils that shift and focus independently, smile that shows too many teeth in multiple rows, pickpocket accomplice with characteristic demon features hidden beneath human appearance - pointed ears that twitch, backwards-bending joints, shadow that reveals true animal form with tail and claws, crowd of onlookers each showing different stages of transformation based on their gullibility - most naive developing sheep-like features with wool growing on arms, greedy growing pig snouts while reaching for purses, prideful sprouting peacock feathers from their clothing, symbolic owl perched nearby as one of wise-fool creatures with human-like intelligence and knowing expression, conjurer's table displaying magical implements that are actually organic creatures disguised as objects - cups that breathe with tiny nostrils, balls that have eyes that blink, wands that are serpents in disguise with scales barely visible, background figures engaged in various forms of deception, each revealing their true nature through animal transformations - card cheats with fox features and bushy tails, false merchants with weasel characteristics and pointed snouts, corrupt officials with vulture necks and bald heads, moral allegory about human susceptibility to illusion shown through gradual transformation of audience members into appropriate animals representing their spiritual weaknesses, hidden creatures throughout scene - demons of deception with chameleon abilities, spirits of gullibility as sheep-human hybrids, entities of greed as pig-faced humanoids, 8K hyperrealistic detail capturing every facial expression showing progression from human to animal nature and complete catalog of moral creatures",
    }

    if (scenarioPrompts[scenario]) {
      prompt += ", " + scenarioPrompts[scenario]
    }
  }

  // Add scenario-specific details for Bosch dataset
  if (dataset === "bosch") {
    const scenarioPrompts: Record<string, string> = {
      pure: "pure mathematical beauty with Boschian surreal precision and fantastical creature elements",
      "garden-earthly-delights":
        "GODLEVEL BOSCH GARDEN OF EARTHLY DELIGHTS: Hieronymus Bosch's masterpiece triptych with iconic fantastical creatures, left panel showing Adam and Eve in pristine Garden of Eden with exotic hybrid animals - elephant-like creatures with castle towers on their backs, giraffe-necked beasts with human intelligence, fish-birds with translucent wings flying through crystalline air, God presenting Eve while strange creatures emerge from caves and crystal pools, middle panel exploding with naked humans riding giant strawberries and oversized fish through coral-pink landscapes, the famous tree-man with hollow egg-shaped body and branch legs standing in central lake, people emerging from and disappearing into giant mussel shells and transparent spheres, couples trapped inside glass bubbles floating through surreal gardens, riders on fantastic boar-fish hybrids and bird-headed quadrupeds, the iconic central fountain with nude figures dancing around pink tower topped with crescent moon, right panel depicting Hell with Bosch's terrifying demon orchestra - the famous bird-headed monster with human body devouring and excreting human souls, musical instruments transformed into torture devices with people trapped inside harps and drums, the knife-eared creature with bagpipe body and human legs, demons with human heads and animal bodies playing discordant music on bone instruments, burning cities reflected in dark waters, hybrid creatures with insect wings and mammalian bodies, organic architecture that breathes and bleeds, every detail painted with Bosch's characteristic precision showing scales, feathers, and human flesh with equal hyperrealistic clarity, 8K resolution capturing every symbolic creature and surreal transformation",
      "temptation-saint-anthony":
        "GODLEVEL BOSCH TEMPTATION OF SAINT ANTHONY: Hieronymus Bosch's nightmarish vision with most terrifying demon creations, Saint Anthony surrounded by signature hybrid monsters - famous fish-headed demons with human torsos and bird legs carrying the saint through apocalyptic skies, grotesque creatures with pig snouts and human hands emerging from burning ruins, iconic toad-like demons with bloated bellies and spindly limbs, demons disguised as beautiful women with hidden animal features - serpent tails coiling beneath silk robes, bird claws instead of hands, insect wings folded behind backs, characteristic egg-shaped creatures with human faces and stick-thin legs dancing in demonic processions, flying demons with bat wings and human heads playing discordant music on instruments made from bones and organs, famous hollow-tree demons with gaping mouths in their torsos containing smaller demons and tortured souls, creatures with multiple heads - human, animal, and bird - all speaking blasphemies in different tongues, demons with backwards feet and upside-down faces crawling on ceilings, signature monster with funnel-shaped head and ladder-like body, organic architecture that breathes and bleeds with windows that are eyes and doors that are mouths, demons emerging from split-open fruits and vegetables like rotten pomegranates birthing imps, terrifying bird-beaked creatures with human intelligence gleaming in their eyes, Saint Anthony maintaining divine composure while reading sacred texts as supernatural chaos swirls around him, every demon rendered with meticulous attention to anatomical impossibility yet convincing detail, 8K hyperrealistic precision showing every scale, feather, and grotesque transformation",
      "ship-fools":
        "GODLEVEL BOSCH SHIP OF FOOLS: Hieronymus Bosch's Ship of Fools populated with characteristic human-animal hybrids and moral grotesques, overcrowded boat filled with signature figures - monks with pig faces representing gluttony, their snouts dripping with wine and food, nuns with bird beaks symbolizing gossip and chatter, their beaks opening to reveal forked tongues, passengers with fish heads gasping for spiritual water while drowning in earthly wine, gills flapping uselessly in air, famous fool with funnel hat and egg-shaped body playing discordant music on organic instruments, demons disguised as merchants with coin-filled transparent bellies and claw hands counting money, creatures with human torsos and animal legs dancing drunkenly on deck - goat legs, horse hooves, bird talons, characteristic owl of false wisdom perched on mast with human-like intelligence and knowing smirk in its eyes, passengers transforming into their inner animal natures - becoming pigs with human hands still grasping wine cups, donkeys with human faces braying moral platitudes, birds with human bodies pecking at each other, ship's hull decorated with organic motifs that seem alive and breathing - carved faces that blink and mouths that whisper, water surrounding vessel filled with floating symbols of vanity - mirrors reflecting demon faces instead of human ones, crowns worn by fish swimming in circles, musical instruments played by sea creatures with human fingers, distant shoreline showing impossible architecture with towers that are giant musical instruments and buildings with faces that sing, tree-mast bearing fruits that are human heads in various expressions of folly - some laughing, some crying, some screaming, each passenger representing different interpretation of human vice with animal characteristics becoming more pronounced as moral decay progresses, 8K resolution showing every grotesque detail and symbolic transformation with signature precision",
      "seven-deadly-sins":
        "GODLEVEL BOSCH SEVEN DEADLY SINS WHEEL: Hieronymus Bosch's circular composition with signature creatures representing moral failure, central eye of God watching over humanity's transgressions with Christ emerging from pupil surrounded by angelic-demonic hybrids, seven segments radiating outward each illustrating different sin through detailed vignettes with Bosch's characteristic monsters, Pride shown through woman admiring reflection held by demon with bird head and human hands while mirror reveals her true animal nature - pig snout and peacock feathers, Envy depicted as neighbors coveting possessions with green-faced demons with elongated necks and grasping claws stoking jealousy between people transforming into envious beasts, Wrath illustrated through tavern brawl where participants are becoming their inner animals - pig-faced gluttons wielding kitchen knives, wolf-headed aggressors with human hands, bird-beaked screamers with talons extended, Sloth showing lazy figure surrounded by characteristic snail-demons and slug-creatures representing spiritual lethargy, creatures with human faces but gastropod bodies leaving trails of moral decay, Greed featuring merchant with coin-filled transparent belly while money-demons with insect features and claw hands count coins with mathematical precision, Gluttony displaying feast where diners are transforming into the animals they consume - pig snouts emerging from human faces, fish gills opening on necks, bird beaks replacing human mouths, Lust revealing couples in compromising positions observed by voyeuristic demons with multiple eyes and elongated necks, telescoping appendages for spying, four corner medallions showing Death as skeleton with signature scythe-wings, Judgment with Christ surrounded by hybrid angel-demons with both holy and demonic features, Hell populated with most creative torture-demons, and Glory with saints who retain subtle animal characteristics representing their spiritual virtues, every scene filled with impossible creatures that blend human intelligence with animal instincts, 8K hyperrealistic detail showing every moral transformation and demonic feature",
      "haywain-triptych":
        "GODLEVEL BOSCH HAYWAIN TRIPTYCH: Hieronymus Bosch's Haywain featuring signature human-animal transformations and demonic creatures, left panel showing Creation with rebel angels transforming into characteristic insect-demons, bird-headed fallen angels with human torsos, hybrid creatures with human intelligence but animal bodies, central panel dominated by massive hay wagon pulled by signature demons disguised as ordinary beasts but with human intelligence gleaming in their eyes and hidden claws beneath fur, crowds of people from all social classes desperately grabbing hay while gradually transforming into their inner animal natures - nobles becoming preening peacocks with human hands, merchants growing pig snouts while counting coins, clergy developing bird beaks for pecking at worldly goods, Pope and Emperor following wagon on horseback while their mounts reveal demonic features - horse heads with human eyes and knowing expressions, lovers on haystack oblivious to spiritual danger while voyeuristic demons with telescoping necks and multiple eyes observe from hidden positions in the hay, demon musicians playing organic instruments that are part plant, part animal, part human anatomy - drums made from human torsos, flutes carved from bones, right panel revealing Hell as ultimate bestiary with burning landscape populated by most creative torture-demons - creatures with musical instrument bodies operating mechanical torture devices, bird-headed monsters with human hands and opposable thumbs, demons with transparent bellies showing their victims being digested, architectural impossibilities with buildings that are giant creatures with window-eyes and door-mouths, every figure throughout triptych showing genius for revealing inner spiritual state through gradual physical transformation into appropriate animal form, 8K resolution capturing every detail of moral metamorphosis and demonic creativity",
      "last-judgment":
        "GODLEVEL BOSCH LAST JUDGMENT: Hieronymus Bosch's terrifying Last Judgment with most creative demonic creatures and hybrid beings, Christ as judge displaying crucifixion wounds while surrounded by signature angel-demon hybrids with subtle animal features - wings that are part feather, part bat membrane, faces that blend human beauty with predatory bird characteristics, Virgin Mary and John the Baptist with characteristic blend of human beauty and otherworldly strangeness, angels blowing trumpets that are part instrument, part organic creature with breathing holes and pulsing veins, resurrected souls emerging from earth in various states of transformation - some retaining human form, others revealing their true animal natures based on earthly sins, blessed souls ascending toward heavenly light guided by benevolent angel-creatures with bird wings but human compassion in their eyes, damned souls dragged downward by most inventive demons - creatures with multiple heads (human, animal, insect), transparent bodies showing internal organs and digestive systems, limbs that are musical instruments playing eternal discord, fantastical punishments matching earthly crimes with creative torture-demons using organic instruments of torment, hybrid demon creatures with animal heads and human bodies administering eternal justice with tools that are part of their anatomy, landscape divided between heavenly paradise populated with gentle hybrid creatures and hellish wasteland filled with nightmarish creations, architectural marvels in heaven that are living creatures with beneficial purposes contrasting with Hell's buildings that are giant demons with window-eyes and door-mouths, saints and martyrs surrounding Christ's throne displaying instruments of martyrdom while showing subtle animal characteristics representing their spiritual virtues, 8K hyperrealistic detail capturing every soul's transformation and complete bestiary of moral creatures",
      "death-miser":
        "GODLEVEL BOSCH DEATH AND THE MISER: Hieronymus Bosch's Death and the Miser with signature demonic tempters and moral creatures, dying miser in bed reaching toward bag of gold while his body shows signs of transformation into his true animal nature - developing pig-like features representing greed, snout elongating and skin becoming coarse, angel pointing toward crucifix with characteristic blend of human beauty and bird-like ethereal qualities, Death entering chamber as skeleton with signature additions - crow wings sprouting from shoulder blades, serpent tail coiled beneath robes, human intelligence gleaming in empty eye sockets, demon emerging from beneath bed as one of classic tempter-creatures with human torso, animal legs ending in cloven hooves, seductive human face hiding predatory animal teeth, room filled with symbols of worldly wealth that reveal their true nature under vision - coins that are demon eyes blinking and watching, jewelry that writhes like living serpents, fine fabrics that show patterns of human faces in torment, younger version of miser in background storing gold in chest while characteristic money-demons with insect features and transparent bellies full of coins whisper encouragement with forked tongues, moral choice visualized through miser's gesture reaching simultaneously toward money (guarded by pig-faced greed demons) and salvation (protected by dove-winged mercy angels), architectural details showing luxury household where every ornate furnishing contains hidden creatures - chair legs that are demon claws, tapestries that show scenes of moral transformation, symbolic objects throughout room representing vanity's true nature - mirrors reflecting animal faces instead of human ones, books whose pages flutter like bat wings, 8K resolution showing every symbolic detail and complete moral bestiary",
      conjurer:
        "GODLEVEL BOSCH THE CONJURER: Hieronymus Bosch's satirical Conjurer scene with signature trickster creatures and moral grotesques, central conjurer performing cup-and-ball trick while his true nature revealed through subtle animal features - elongated fingers like bird talons, eyes with reptilian pupils that shift and focus independently, smile that shows too many teeth in multiple rows, pickpocket accomplice with characteristic demon features hidden beneath human appearance - pointed ears that twitch, backwards-bending joints, shadow that reveals true animal form with tail and claws, crowd of onlookers each showing different stages of transformation based on their gullibility - most naive developing sheep-like features with wool growing on arms, greedy growing pig snouts while reaching for purses, prideful sprouting peacock feathers from their clothing, symbolic owl perched nearby as one of wise-fool creatures with human-like intelligence and knowing expression, conjurer's table displaying magical implements that are actually organic creatures disguised as objects - cups that breathe with tiny nostrils, balls that have eyes that blink, wands that are serpents in disguise with scales barely visible, background figures engaged in various forms of deception, each revealing their true nature through animal transformations - card cheats with fox features and bushy tails, false merchants with weasel characteristics and pointed snouts, corrupt officials with vulture necks and bald heads, moral allegory about human susceptibility to illusion shown through gradual transformation of audience members into appropriate animals representing their spiritual weaknesses, hidden creatures throughout scene - demons of deception with chameleon abilities, spirits of gullibility as sheep-human hybrids, entities of greed as pig-faced humanoids, 8K hyperrealistic detail capturing every facial expression showing progression from human to animal nature and complete catalog of moral creatures",
      "stone-operation":
        "GODLEVEL BOSCH STONE OF MADNESS: Hieronymus Bosch's satirical Stone of Madness with signature medical demons and folly creatures, quack surgeon wearing funnel hat (revealing his empty-headed nature) with subtle demon features - elongated fingers with too many joints, predatory smile showing pointed teeth, eyes that reflect his true parasitic nature like an insect's compound eyes, patient seated in chair with head bandaged while flower emerges instead of stone, his face showing transformation into sheep-like features representing gullibility - wool growing on cheeks, rectangular pupils, audience including nun and monk observing procedure with characteristic religious figures who show subtle animal traits - nun with bird-like neck representing gossip, elongated and flexible, monk with pig features representing gluttony, snout barely concealed by hood, Latin inscription surrounded by decorative creatures that seem to writhe and move, medical instruments displayed prominently but revealed as organic torture devices - scalpels that are demon claws still attached to invisible hands, forceps that are insect mandibles clicking together, bandages that are serpent skins still moving, landscape background showing normal life continuing while populated with subtle background creatures - trees with face-like bark patterns that blink, clouds that form demon shapes, birds that have human expressions and knowing looks, symbolic funnel representing empty-headedness while containing tiny demons of ignorance crawling inside, flower symbolizing natural growth versus artificial intervention, blooming with faces of nature spirits, detailed facial expressions revealing character through animal transformations - doctor's predatory bird features, patient's sheep-like innocence, observers' various animal characteristics based on their spiritual weaknesses, social commentary on medical charlatanry expressed through complete bestiary of deception demons, healing spirits, and folly creatures, 8K resolution showing every symbolic creature and moral transformation",
      "adoration-magi":
        "GODLEVEL BOSCH ADORATION OF MAGI: Hieronymus Bosch's unique Adoration blending traditional nativity with signature fantastical creatures, three wise men presenting gifts while showing subtle characteristics - Melchior with bird-like wisdom in his eyes, pupils that reflect infinite knowledge, Caspar with serpent-like knowledge coiled in his posture, movements that suggest hidden scales, Balthazar with lion-hearted courage in his bearing, mane-like hair and predatory grace, Virgin Mary holding Christ child in humble stable while protective angel-creatures with animal features guard the holy family - dove-winged seraphim with human faces, lamb-bodied cherubim with golden fleece, lion-faced guardians with manes of light, Joseph standing protectively while mysterious figures peer through stable openings - some benevolent spirits with gentle animal features, others testing demons with predatory characteristics barely concealed, background landscape filled with characteristic hybrid creatures representing cosmic significance of Christ's birth - angel-birds singing celestial music with human voices, demon-beasts fleeing from divine light with animal bodies and human intelligence, impossible architecture combining realistic stable with organic buildings that breathe and pulse, symbolic gifts of gold, frankincense, and myrrh guarded by treasure-spirits with crystalline bodies and gem-like eyes, angels hovering overhead as most beautiful human-animal hybrids with peacock wings for glory, swan necks for purity, lion hearts for courage, demonic figures hidden in shadows representing evil's presence even at Christ's birth - serpent-demons coiled in dark corners with human faces, bat-winged tempters lurking in rafters with glowing eyes, but all held at bay by divine light, exotic animals from distant lands accompanying magi's caravan - interpretation of camels with human intelligence and knowing expressions, elephants with castle-towers and human architects visible in windows, birds with prophetic abilities speaking in human tongues, 8K hyperrealistic resolution capturing every symbolic creature and devotional detail",
      "christ-carrying-cross":
        "GODLEVEL BOSCH CHRIST CARRYING CROSS: Hieronymus Bosch's intense Christ Carrying Cross with masterful grotesque faces and human-demon transformations, central figure of Christ with serene divine expression surrounded by crowd of distorted faces showing genius for revealing inner spiritual state through physical transformation, tormentors with faces gradually becoming their true animal natures - soldiers with wolf-like predatory features, elongated snouts and yellow fangs, mockers with hyena grins and elongated necks that stretch unnaturally, sadists with vulture beaks and reptilian eyes that never blink, crowd showing various expressions of cruelty where human features blend with appropriate animal characteristics - pig snouts for gluttony, dripping with saliva, fox features for cunning with pointed ears and narrow eyes, rat-like teeth for meanness, constantly gnawing, two thieves visible with contrasting transformations - repentant thief retaining human dignity with subtle lamb-like gentleness in his eyes, defiant thief showing demonic features with bat-wing ears and serpent tongue flicking out, detailed physiognomy studies revealing inner character through signature animal-human blends - each wrinkle and expression line showing moral decay or spiritual grace, symbolic elements including crown of thorns that seems alive with tiny thorn-demons, instruments of passion guarded by both angel-spirits and demon-tempters, masterful psychological portraiture showing complete spectrum of human nature from Christ's divine humanity to surrounding crowd's animal degradation, rich symbolism with each face representing different aspect of humanity's response to divine sacrifice through appropriate animal transformation, composition creating claustrophobic effect emphasizing Christ's isolation among menagerie of human-beasts, moral commentary on human capacity for both cruelty and redemption expressed through gradual transformation from human to animal features, 8K hyperrealistic detail showing every wrinkle, animal feature, and symbolic transformation in profound meditation on human nature through complete bestiary of moral creatures",
    }

    if (scenarioPrompts[scenario]) {
      prompt += ", " + scenarioPrompts[scenario]
    }
  }

  if (dataset === "diffusion") {
    const scenarioPrompts: Record<string, string> = {
      pure: "Reaction-diffusion systems with pattern formation, chemical patterns, Turing patterns, mathematical biology, emergent patterns, natural mathematics, biological computation, self-organization",
      "origami-world":
        "Dynamic origami reaction-diffusion patterns with paper-folded chemical-inspired designs, delicate paper structures showing Turing patterns, origami interpretation of self-organization, handmade paper demonstrating pattern formation mathematics, warm lighting revealing biological patterns through paper shadows, visible fold lines emphasizing reaction boundaries, masterful origami engineering translating chemical patterns into paper art, traditional Japanese paper folding techniques applied to biological mathematics, paper sculpture pattern mastery, godlevel reaction origami excellence",
      "animal-transport":
        "Transportation on leopard with coat patterns showing reaction-diffusion mathematics, leopard spots created by Turing pattern formation, riders navigating pattern formation landscape on leopard back, mathematical precision in spot development, reaction-diffusion embodied in animal markings, biological pattern formation in transport, mathematical chemistry in leopard anatomy, Turing patterns in animal transport, natural mathematics in biological systems, godlevel reaction-diffusion animal transport excellence",
    }

    if (scenarioPrompts[scenario]) {
      prompt += ", " + scenarioPrompts[scenario]
    }
  }

  // Add color scheme
  const colorPrompts: Record<string, string> = {
    plasma: "vibrant plasma colors, electric blues and magentas",
    quantum: "quantum field colors, deep blues and ethereal whites",
    cosmic: "cosmic colors, deep space purples and stellar golds",
    thermal: "thermal imaging colors, heat signature reds and oranges",
    spectral: "full spectrum rainbow colors, prismatic light effects",
    crystalline: "crystalline colors, clear gems and mineral tones",
    bioluminescent: "bioluminescent colors, glowing organic blues and greens",
    aurora: "aurora borealis colors, dancing green and purple lights",
    metallic: "metallic tones, silver and bronze accents",
    prismatic: "prismatic light effects, rainbow refractions",
    monochromatic: "monochromatic grayscale, black and white tones",
    infrared: "infrared heat colors, thermal reds and oranges",
    lava: "molten lava colors, glowing reds and oranges",
    futuristic: "futuristic neon colors, cyberpunk aesthetics",
    forest: "forest greens and earth tones",
    ocean: "ocean blues and aqua tones",
    sunset: "warm sunset colors, oranges and deep reds",
    arctic: "arctic colors, ice blues and pristine whites",
    neon: "bright neon colors, electric pinks and greens",
    vintage: "vintage sepia tones, aged photograph aesthetics",
    toxic: "toxic waste colors, radioactive greens and yellows",
    ember: "glowing ember colors, warm orange and red coals",
    lunar: "lunar surface colors, silver grays and crater shadows",
    tidal: "tidal pool colors, ocean blues and sandy browns",
  }

  prompt += `, ${colorPrompts[colorScheme] || "vibrant colors"}`

  // Add artistic quality descriptors
  prompt +=
    ", highly detailed, artistic masterpiece, professional photography quality, 8K resolution, stunning visual composition"

  return prompt
}

import { generateFlowField, type GenerationParams } from "@/lib/flow-model"

export const runtime = "edge"

export async function POST(req: Request): Promise<NextResponse> {
  try {
    const body = await req.json()
    const { dataset, scenario, colorScheme, seed, numSamples, noiseScale, timeStep } = body as GenerationParams

    console.log("Generating flow field with params:", {
      dataset,
      scenario,
      colorScheme,
      seed,
      numSamples,
      noiseScale,
      timeStep,
    })

    const svgContent = generateFlowField({
      dataset,
      scenario,
      colorScheme,
      seed,
      numSamples,
      noiseScale,
      timeStep,
    })

    return NextResponse.json({ svgContent }, { status: 200 })
  } catch (error: any) {
    console.error("Error generating flow field:", error)
    return NextResponse.json({ error: error.message || "Failed to generate flow field" }, { status: 500 })
  }
}
