-- Disable RLS on all tables

ALTER TABLE aspect_ratios DISABLE ROW LEVEL SECURITY;
ALTER TABLE collection_sketches DISABLE ROW LEVEL SECURITY;
ALTER TABLE collections DISABLE ROW LEVEL SECURITY;
ALTER TABLE color_schemes DISABLE ROW LEVEL SECURITY;
ALTER TABLE datasets DISABLE ROW LEVEL SECURITY;
ALTER TABLE generation_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE scenarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE sketches DISABLE ROW LEVEL SECURITY;
